name: E2E Tests

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to run tests against'
                type: environment
                required: true
                default: 'default-private'
            node_urls:
                description: 'Optional: Override the environment node URLs. (Comma separated)'
                type: string
                required: false
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - '*'

permissions:
    checks: write
    pull-requests: write

jobs:
    e2e_tests:
        name: Run E2E Tests
        # https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html#sample-github-action-runners-create-project
        # large = 15 GB memory, 8 vCPUs
        # 7.0 = Ubuntu 22.04
        runs-on: codebuild-ThorE2E-GHA-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-large
        environment: ${{ inputs.environment || 'default-private' }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install Node Modules
              run: yarn install

            - name: Run Tests
              run: |
                  yarn docker:up
                  yarn test
              env:
                  # use the provided node_urls or the default NODE_URLS
                  NODE_URLS: ${{ inputs.node_urls || vars.NODE_URLS }}
                  PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS }}
                  MNEMONIC: ${{ secrets.MNEMONIC }}
                  NETWORK_TYPE: ${{ inputs.environment }}

            - name: Publish Results
              uses: dorny/test-reporter@v1
              id: test-reporter
              if: ${{ github.repository == 'vechain/thor-e2e-tests' && (success() || failure()) }}
              with:
                  name: E2E Test Report
                  only-summary: 'false'
                  list-suites: 'all'
                  list-tests: 'all'
                  fail-on-error: 'true'
                  reporter: 'jest-junit'
                  path: |
                      junit.xml
